## The Power of NumPy

In [3]:
range(0, 5)

range(0, 5)

In [5]:
list(range(0, 5))

[0, 1, 2, 3, 4]

In [4]:
list(range(0, 5, 2))

[0, 2, 4]

In [15]:
list1 = [1, 3, 5, 7, 9]
list2 = [2, 4, 6, 8, 10]

In [7]:
list1 * list2

TypeError: can't multiply sequence by non-int of type 'list'

In [18]:
new_list = []

for i in range(0, len(list1)):
    x = list1[i] * list2[i]
    new_list.append(x)

print(new_list)

[2, 12, 30, 56, 90]


In [29]:
import numpy as np

In [30]:
x = np.array([1, 3, 5, 7, 9])
y = np.array([2, 4, 6, 8, 10])

In [31]:
print(type(x))

<class 'numpy.ndarray'>


In [32]:
x * y

array([ 2, 12, 30, 56, 90])

## Creating NumPy Array with The Array() Function

In [33]:
import numpy as np

In [34]:
np.array([2, 4, 6, 8])

array([2, 4, 6, 8])

In [35]:
variable = [5.8, 9, 7, 5]

In [44]:
print(type(variable[0]))
print(type(variable[1]))

<class 'float'>
<class 'int'>


In [54]:
new_variable = np.array([5.8, 9, 7, 5])

In [55]:
new_variable

array([5.8, 9. , 7. , 5. ])

In [51]:
print(type(new_variable[0]))
print(type(new_variable[1]))

<class 'numpy.float64'>
<class 'numpy.float64'>


In [86]:
new_variable2 = np.array([5.8, 9, 7, 5], dtype = "int")

In [87]:
new_variable2

array([5, 9, 7, 5])

## Creating NumPy Array with The Zeros() Function

In [94]:
import numpy as np

In [96]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [108]:
np.zeros((3, 5), dtype = "int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## Creating NumPy Array with The Ones() Function

In [109]:
import numpy as np

In [119]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [125]:
np.ones((3, 4, 5), dtype = "int")

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

## Creating NumPy Array with The Full() Function

In [121]:
import numpy as np

In [126]:
np.full(8, 5)

array([5, 5, 5, 5, 5, 5, 5, 5])

In [127]:
np.full((2, 3), 6, dtype = "float")

array([[6., 6., 6.],
       [6., 6., 6.]])

## Creating NumPy Array with The Arange() Function

In [128]:
import numpy as np

In [132]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [147]:
example = np.arange(3, 10, dtype = "float")

In [134]:
print(example)

[3. 4. 5. 6. 7. 8. 9.]


In [138]:
type(example)

numpy.ndarray

## Creating NumPy Array with The Eye() Function

In [160]:
import numpy as np

In [165]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [169]:
np.eye(3, 2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [167]:
np.eye(3, 2, dtype = "bool")

array([[ True, False],
       [False,  True],
       [False, False]])

## Creating NumPy Array with The Linspace() Function

In [140]:
import numpy as np

In [143]:
np.linspace(10, 30, 10)

array([10.        , 12.22222222, 14.44444444, 16.66666667, 18.88888889,
       21.11111111, 23.33333333, 25.55555556, 27.77777778, 30.        ])

## Creating NumPy Array with The Random() Function

In [1]:
import numpy as np

In [174]:
# rand function
np.random.rand(5)

array([0.19430083, 0.40303108, 0.41355138, 0.29581052, 0.19316643])

In [173]:
np.random.rand(2,3)

array([[0.1468043 , 0.27561503, 0.42224776],
       [0.03940202, 0.21680778, 0.59286061]])

In [175]:
# randn function
np.random.randn(5)

array([-0.5609546 , -0.8936212 ,  0.0727686 ,  0.1012028 , -0.79881207])

In [180]:
np.random.randn(2, 3)

array([[ 0.56648369, -2.39850786,  1.31479531],
       [-0.857381  , -0.58586345, -0.32406874]])

In [145]:
# random.normal function
np.random.normal(20, 5, (4, 3))

array([[24.76938714, 19.58387665, 23.55492497],
       [ 8.67280626, 15.19093351, 15.50564265],
       [20.11104925, 10.21087307, 21.86794148],
       [27.78422772, 29.91420724, 27.76603207]])

In [151]:
# randint function
np.random.randint(0, 10, (4, 4))

array([[8, 8, 5, 7],
       [5, 8, 6, 9],
       [0, 1, 2, 4],
       [4, 2, 9, 8]])

## Properties of NumPy Array

In [1]:
import numpy as np

In [10]:
matrix = np.random.randint(10, 50, (5, 4))

In [11]:
matrix

array([[22, 44, 37, 40],
       [25, 31, 49, 17],
       [42, 32, 25, 16],
       [36, 16, 31, 34],
       [23, 21, 27, 49]])

In [12]:
matrix.ndim

2

In [13]:
matrix.shape

(5, 4)

In [14]:
matrix.size

20

In [15]:
matrix.dtype

dtype('int32')

## Reshaping a NumPy Array: Reshape() Function

In [46]:
import numpy as np

In [61]:
example = np.arange(1, 16)

In [62]:
example

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [66]:
example.reshape((3, 5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [68]:
array = example.reshape((1, 15))

In [69]:
array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [70]:
example.ndim

1

In [71]:
array.ndim

2

In [72]:
example

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [73]:
example.reshape((4, 3))

ValueError: cannot reshape array of size 15 into shape (4,3)

## Identifying the Largest Element of a Numpy Array: Max(), Argmax() Functions

In [6]:
import numpy as np

In [28]:
array = np.random.randint(0, 50, 10)

In [29]:
array

array([ 5, 32, 28,  1, 16, 12, 47, 26, 23, 36])

In [30]:
array.max()

47

In [31]:
array.argmax()

6

In [24]:
array2 = np.random.randint(0, 50, (4, 3))

In [25]:
array2

array([[ 6, 42, 32],
       [40, 49, 14],
       [35, 22, 12],
       [29, 41,  1]])

In [32]:
array2.max()

49

In [33]:
array2.argmax()

4

## Detecting Least Element of Numpy Array: Min(), Argmin() Functions

In [34]:
import numpy as np

In [36]:
array = np.random.randint(20, 70, 10)

In [37]:
array

array([67, 48, 67, 21, 47, 32, 52, 67, 49, 58])

In [38]:
array.min()

21

In [39]:
array.argmin()

3

In [42]:
array2 = np.random.randint(20, 70, (5, 3))

In [43]:
array2

array([[29, 35, 35],
       [22, 69, 63],
       [48, 50, 52],
       [69, 24, 54],
       [29, 52, 60]])

In [44]:
array2.min()

22

In [45]:
array2.argmin()

3

## Concatenating Numpy Arrays: Concatenate() Function

In [1]:
import numpy as np

In [5]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

In [8]:
np.concatenate([array1, array2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
array3 = np.arange(1, 7).reshape((2, 3))

In [18]:
array3

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
array4 = np.array([[7, 8, 9], [10, 11, 12]])

In [20]:
array4 

array([[ 7,  8,  9],
       [10, 11, 12]])

In [23]:
np.concatenate([array3, array4])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
np.concatenate([array3, array4], axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [26]:
np.concatenate([array1, array3])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [31]:
array5 = np.arange(1,11).reshape(5, 2)

In [32]:
array5 

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [33]:
np.concatenate([array3, array5])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

## Splitting One-Dimensional Numpy Arrays: The Split() Function

In [34]:
import numpy as np

In [36]:
array = np.array([1, 3, 5, 50, 50 , 2, 4, 6])

In [43]:
np.split(array, [3, 5])

[array([1, 3, 5]), array([50, 50]), array([2, 4, 6])]

In [44]:
x, y, z = np.split(array, [3, 5])

In [45]:
x

array([1, 3, 5])

In [46]:
y

array([50, 50])

In [47]:
z

array([2, 4, 6])

In [49]:
np.split(array, 4)

[array([1, 3]), array([ 5, 50]), array([50,  2]), array([4, 6])]

In [50]:
np.split(array, 5)

ValueError: array split does not result in an equal division

## Splitting Two-Dimensional Numpy Arrays: Split(), Vsplit, Hsplit() Function

In [54]:
import numpy as np

In [55]:
array = np.arange(20).reshape(5, 4)

In [53]:
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [61]:
np.split(array, [1, 3])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [62]:
x, y, z = np.split(array, [1, 3])

In [63]:
x

array([[0, 1, 2, 3]])

In [64]:
y

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
z

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [66]:
np.split(array, [1, 3], axis = 1)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [68]:
# hsplit() function

In [69]:
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [70]:
np.hsplit(array, 4)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [71]:
np.hsplit(array, [1, 3]) 

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [ ]:
# vsplit() function

In [72]:
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [73]:
np.vsplit(array, 5)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [74]:
np.vsplit(array, [2, 4])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

## Sorting Numpy Arrays: Sort() Function

In [75]:
import numpy as np

In [76]:
variable = np.array([3, 5, 1, 8, 6, 2, 9])

In [77]:
variable

array([3, 5, 1, 8, 6, 2, 9])

In [82]:
np.sort(variable)

array([1, 2, 3, 5, 6, 8, 9])

In [83]:
variable

array([3, 5, 1, 8, 6, 2, 9])

In [84]:
variable2 = np.sort(variable)

In [85]:
variable2

array([1, 2, 3, 5, 6, 8, 9])

In [80]:
example = np.random.normal(30, 10, (4, 4))

In [81]:
example

array([[16.44512566, 34.28032044, 36.86149237, 25.83105961],
       [28.08051261, 21.46830629, 43.07369168, 23.81026274],
       [49.78690423,  8.42467689, 31.2169405 , 34.299648  ],
       [33.0152012 , 29.64390332, 34.33549742, 30.84628751]])

In [86]:
np.sort(example, axis = 0)

array([[16.44512566,  8.42467689, 31.2169405 , 23.81026274],
       [28.08051261, 21.46830629, 34.33549742, 25.83105961],
       [33.0152012 , 29.64390332, 36.86149237, 30.84628751],
       [49.78690423, 34.28032044, 43.07369168, 34.299648  ]])

In [87]:
np.sort(example, axis = 1)

array([[16.44512566, 25.83105961, 34.28032044, 36.86149237],
       [21.46830629, 23.81026274, 28.08051261, 43.07369168],
       [ 8.42467689, 31.2169405 , 34.299648  , 49.78690423],
       [29.64390332, 30.84628751, 33.0152012 , 34.33549742]])