## Indexing Numpy Arrays

In [1]:
import numpy as np

In [3]:
array = np.arange(0, 11)

In [4]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
array[4]

4

In [6]:
array[-2]

9

In [7]:
variable = np.array([[5, 10, 15],
                     [20, 25, 30],
                     [35, 40, 45]])

In [8]:
variable

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [9]:
variable[0, 0]

5

In [10]:
variable[2, 1]

40

In [13]:
variable[-1, -3]

35

## Slicing One-Dimensional Numpy Arrays

In [14]:
import numpy as np

In [19]:
example = np.arange(10, 20)

In [20]:
example

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
example[2:6]

array([12, 13, 14, 15])

In [23]:
example[3::2]

array([13, 15, 17, 19])

In [24]:
example[:7:3]

array([10, 13, 16])

## Slicing Two-Dimensional Numpy Arrays

In [25]:
import numpy as np

In [26]:
array = np.arange(30).reshape(6, 5)

In [27]:
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [39]:
array[2, :]

array([10, 11, 12, 13, 14])

In [40]:
array[2]

array([10, 11, 12, 13, 14])

In [41]:
array[0]

array([0, 1, 2, 3, 4])

In [42]:
array[:, 2]

array([ 2,  7, 12, 17, 22, 27])

In [43]:
array[:, 0]

array([ 0,  5, 10, 15, 20, 25])

In [44]:
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [45]:
array[1:4, 0:3]

array([[ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17]])

In [46]:
array[0::2, 0::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

## Assigning Value to One-Dimensional Arrays

In [4]:
import numpy as np 

In [57]:
variable = np.array([0, 1, 2, 3, 7, 5, 6, 9, 8, 9])

In [58]:
variable

array([0, 1, 2, 3, 7, 5, 6, 9, 8, 9])

In [59]:
variable[4] = 4

In [60]:
variable[7] = 7

In [61]:
variable

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
variable[0:5] = 10

In [63]:
variable

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9])

In [64]:
variable[5:]

array([5, 6, 7, 8, 9])

In [65]:
variable[5:] = 20, 30, 40, 50, 60

In [66]:
variable

array([10, 10, 10, 10, 10, 20, 30, 40, 50, 60])

## Assigning Value to Two-Dimensional Arrays

In [39]:
import numpy as np

In [40]:
example = np.array([[10, 20, 30], 
                   [40, 50, 60],
                   [70, 80, 90]])

In [41]:
example

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [42]:
example[1, 1] = 100

In [43]:
example

array([[ 10,  20,  30],
       [ 40, 100,  60],
       [ 70,  80,  90]])

In [44]:
example[1, 0] = 100.6

In [45]:
example

array([[ 10,  20,  30],
       [100, 100,  60],
       [ 70,  80,  90]])

In [47]:
example[:, 2] = 100

In [48]:
example

array([[ 10,  20, 100],
       [100, 100, 100],
       [ 70,  80, 100]])

In [49]:
example[0::2, 0:2]

array([[10, 20],
       [70, 80]])

In [50]:
example[0::2, 0:2] = 100

In [51]:
example

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [52]:
example[0]

array([100, 100, 100])

In [53]:
example[0] = 10, 20, 30

In [54]:
example

array([[ 10,  20,  30],
       [100, 100, 100],
       [100, 100, 100]])

## Fancy Indexing of One-Dimensional Arrrays

In [67]:
import numpy as np

In [69]:
fancy = np.arange(0, 50, 5)

In [70]:
fancy

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [71]:
fancy[1]

5

In [72]:
fancy[3]

15

In [73]:
fancy[5]

25

In [74]:
[fancy[1], fancy[3], fancy[5]]

[5, 15, 25]

In [75]:
indexes = [1, 3, 5]

In [76]:
fancy[indexes]

array([ 5, 15, 25])

In [82]:
array = np.array([1, 3, 5])

In [83]:
array

array([1, 3, 5])

In [84]:
fancy[array]

array([ 5, 15, 25])

## Fancy Indexing of Two-Dimensional Arrrays

In [130]:
import numpy as np

In [131]:
variable = np.zeros((10, 10), dtype = "int")

In [132]:
variable

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [133]:
variable.shape

(10, 10)

In [134]:
variable.shape[0]

10

In [135]:
row = variable.shape[0]

In [136]:
for i in range(row):
    variable[i] = i

In [137]:
variable

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [117]:
list1 = [1, 3, 5, 7]

In [118]:
variable[list1]

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [119]:
list2 = [8, 5, 2, 7, 3]

In [120]:
variable[list2]

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [126]:
example = np.arange(1,17).reshape((4,4))

In [122]:
example 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [127]:
example[[0,3], [1,2]]

array([ 2, 15])

In [138]:
row = [0, 2, 3, 1]
column = [3, 0, 2, 1]

In [139]:
example[row, column]

array([ 4,  9, 15,  6])

## Combining Fancy Index with Normal Indexing

In [140]:
import numpy as np

In [141]:
example = np.arange(1,17).reshape((4,4))

In [142]:
example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [144]:
example[1, [1,3]]

array([6, 8])

In [145]:
example[[0, 3], 1]

array([ 2, 14])

## Combining Fancy Index with Normal Slicing

In [146]:
import numpy as np

In [147]:
example = np.arange(1,17).reshape((4,4))

In [148]:
example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [149]:
example[0:, [1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [150]:
example[1:3, [1, 2]]

array([[ 6,  7],
       [10, 11]])

## Operations with Comparison Operators

In [151]:
import numpy as np

In [152]:
array = np.arange(1, 11)

In [153]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [154]:
array > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [155]:
array[array > 5]

array([ 6,  7,  8,  9, 10])

In [156]:
condition = array <= 4

In [157]:
array[condition]

array([1, 2, 3, 4])

In [169]:
new_condition = (array != 8) & (array >= 6)

In [170]:
array[new_condition]

array([ 6,  7,  9, 10])

## Arithmetic Operations in Numpy

In [1]:
import numpy as np

In [172]:
array = np.arange(1, 11)

In [173]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [174]:
array - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [175]:
array * 10 

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [176]:
array / 10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [178]:
((array * 10) + 20) / 5

array([ 6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.])

In [26]:
array * array

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [27]:
array / array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [179]:
np.subtract(array, 2)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [180]:
np.multiply(array, 10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [181]:
np.add(array, 20)

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [183]:
np.divide(array, 10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [184]:
array ** 3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [185]:
np.power(array, 3)

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [2]:
np.sqrt(4)

2.0

In [3]:
np.sqrt(100)

10.0

In [186]:
array % 5

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0], dtype=int32)

In [187]:
np.mod(array, 5)

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0], dtype=int32)

In [199]:
np.sin(180)

-0.8011526357338304

In [200]:
np.cos(180)

-0.5984600690578581

In [201]:
np.log(array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [202]:
np.log10(array)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

## Statistical Operations in Numpy

In [7]:
import numpy as np

In [8]:
array = np.arange(1, 11)

In [9]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.sum(array)

55

In [11]:
np.mean(array)

5.5

In [18]:
np.median(array)

5.5

In [12]:
np.min(array)

1

In [13]:
np.max(array)

10

In [14]:
np.std(array)

2.8722813232690143

In [15]:
np.var(array)

8.25

In [16]:
np.sqrt(np.var(array))

2.8722813232690143

## Solving Second-Degree Equations with NumPy

In [1]:
import numpy as np

 2X1 + X2  = 5

-3X1 + 6X2 = 0

In [2]:
coefficient = np.array([[2, 1], [-3, 6]])

In [3]:
coefficient

array([[ 2,  1],
       [-3,  6]])

In [7]:
output = np.array([5, 0])

In [8]:
output

array([5, 0])

In [9]:
np.linalg.solve(coefficient, output)

array([2., 1.])